name: CI

on:
  push:
    branches:
      - main  # Change to your main branch if different
  pull_request:
    branches:
      - main  # Change to your main branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js (or other environment)
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify your version

      - name: Install dependencies
        run: npm install  # Change command based on your project

      - name: Run tests
        run: npm test  # Change command based on your project
